server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/cosmoofspace2007/config-repo
          default-label: main
pharmacy:
  vat-rate: 10
